#file: noinspection undefined

# profile
ACTIVE_PROFILE: test

# server
SERVER_PORT:

# datasource
POSTGRESQL_HOST:
POSTGRESQL_PORT:
POSTGRESQL_DATABASE:
POSTGRESQL_USERNAME:
POSTGRESQL_PASSWORD:

# keys
KEY_ALGORITHM: RSA
KEY_ID:
PRIVATE_KEY:
PUBLIC_KEY:
